### Drawings Index
GET http://localhost:3000/drawings.json

### Create new
POST http://localhost:3000/drawings.json
Content-Type: application/json

{
  "name": "Test 3",
  "tags": "air water museum",
  "descripton": "The quick brown fox jumps over the lazy dog",
  "url": "https://d1nn9x4fgzyvn4.cloudfront.net/migration-slide-image/19-170_sc235559_4x3.jpg"
}

### Show by ID
GET http://localhost:3000/drawings/18.json


### Update params
PATCH http://localhost:3000/drawings/18.json
Content-Type: application/json

{
  //"tags": "water air museum blue"
  "using_Images": 0
}

### Destroy drawing
DELETE http://localhost:3000/drawings/3.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Kate",
  "password": "TinaKenard",
  "password_confirmation": "TinaKenard"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "name": "Kate",
  "password": "TinaKenard"
}


### Images create
POST http://localhost:3000/images.json
Content-Type: application/json

{
  "url": "https://res.cloudinary.com/dygjz8yhp/image/upload/v1688163406/14_copy_21_fipelf.jpg",
  "description": "test",
  "user_id": 1
}